from __future__ import annotations
import json

from services.cache import get_or_scrape
from services.scraper import BaseScraper

CATEGORIES = ["gpu", "processor", "motherboard", "memory", "storage", "psu", "case", "cooler"]
PRODUCTS_PER_CATEGORY = 10  


MAX_ALTERNATIVES = 3
TIPS_COUNT = 3
MAX_NOTE_CHARS = 260          # per-part "notes" field — loosened, this carries the compatibility reasoning
MAX_SENTENCE_FIELD_CHARS = 200  # summary / feasibility_note / upgrade_path


# ── Shared: build the price block ─────────────────────────────────────────────

async def build_price_block(scrapers: list[BaseScraper]) -> str:
    sections = []
    for category in CATEGORIES:
        products = await get_or_scrape(category, scrapers)
        if not products:
            continue
        products = sorted(products, key=lambda p: p["price_egp"])
        top = products[:PRODUCTS_PER_CATEGORY]
        lines = [
            f"  - {p['name']}: {p['price_egp']:,} EGP (at {p['store']})"
            for p in top
        ]
        sections.append(f"{category.upper()}:\n" + "\n".join(lines))
    return "\n\n".join(sections)


def build_system_prompt(price_block: str) -> str:
    return f"""You are an expert PC builder specializing in the Egyptian market.

LIVE PRICES scraped from EGPrices.com (updated every 6 hours):

{price_block}

RULES:
- Only recommend components from the list above — never invent products or prices
- Include the store name from the data in each part's notes
- A build must include: CPU, Motherboard, RAM, GPU (unless office build), Storage, PSU, Case
- Add a Cooler only if the CPU doesn't include a box cooler
- Ensure CPU and motherboard socket compatibility (e.g. LGA1700 for 13th gen Intel)
- Ensure RAM type matches motherboard (DDR4 vs DDR5)
- Total must not exceed the budget — if impossible, set feasibility to "infeasible"
- Return ONLY a valid JSON object, no markdown, no explanation outside the JSON

LENGTH LIMITS (keep responses concise — this directly affects generation speed):
- Each part's "notes": 1-2 sentences, up to ~40 words. Explain the actual reasoning — why this specific part over similar options, and any compatibility detail that matters (socket, RAM speed, PSU wattage headroom, etc.). Don't just restate the product name.
- "summary", "feasibility_note", "upgrade_path": ONE short sentence each, under 25 words
- "alternatives": at most {MAX_ALTERNATIVES} entries, only for parts genuinely worth swapping — omit if none
- "tips": exactly {TIPS_COUNT} short tips, each under 15 words

JSON structure:
{{
  "summary": "1 sentence overview",
  "feasibility": "feasible" | "tight" | "infeasible",
  "feasibility_note": "1 sentence explanation",
  "total_estimated": <number>,
  "parts": [
    {{
      "category": "CPU" | "Motherboard" | "RAM" | "GPU" | "Storage" | "PSU" | "Case" | "Cooler",
      "name": "exact product name from the list",
      "price_egp": <number>,
      "store": "store name from the list",
      "notes": "1-2 sentences: why this part specifically, plus any compatibility reasoning",
      "egprices_search": "short search term for egprices.com"
    }}
  ],
  "alternatives": [
    {{"part": "category", "alternative": "product name", "reason": "why swap, 1 short phrase"}}
  ],
  "tips": ["tip1", "tip2", "tip3"],
  "upgrade_path": "1 sentence: what to upgrade first when budget allows"
}}"""


def build_user_message(budget: int, use_case: str, priority: str, notes: str) -> str:
    return (
        f"Budget: {budget:,} EGP\n"
        f"Use case: {use_case}\n"
        f"Priority: {priority}\n"
        f"Notes: {notes or 'none'}"
    )


def _truncate(text: str, max_chars: int) -> str:
    if not isinstance(text, str) or len(text) <= max_chars:
        return text
    return text[:max_chars].rstrip() + "…"


def _trim_response(data: dict) -> dict:
    """
    Safety net for models that don't fully follow the LENGTH LIMITS in the
    prompt. Doesn't save generation time (the tokens are already generated by
    the time this runs) — it just guarantees the response schema stays within
    bounds for the frontend, regardless of how well a given provider complies.
    """
    for field in ("summary", "feasibility_note", "upgrade_path"):
        if field in data:
            data[field] = _truncate(data[field], MAX_SENTENCE_FIELD_CHARS)

    if isinstance(data.get("parts"), list):
        for part in data["parts"]:
            if isinstance(part, dict) and "notes" in part:
                part["notes"] = _truncate(part["notes"], MAX_NOTE_CHARS)

    if isinstance(data.get("alternatives"), list):
        data["alternatives"] = data["alternatives"][:MAX_ALTERNATIVES]

    if isinstance(data.get("tips"), list):
        data["tips"] = data["tips"][:TIPS_COUNT]

    return data


def parse_response(text: str) -> dict:
    """Extract JSON from model response regardless of surrounding text."""
    first, last = text.index("{"), text.rindex("}")
    data = json.loads(text[first:last + 1])
    return _trim_response(data)